#!/usr/bin/env bash
# DPLEvolve AE — Shared Environment Variable Resolution
# Source this in all AE scripts to get consistent variable resolution.
#
# Usage:
#   source "${AE_ROOT}/scripts/shared/env_vars.sh"
#   dpl_ae_resolve_env

set -euo pipefail

dpl_ae_resolve_env() {
  # Resolve AE_ROOT from this file's location
  if [[ -z "${AE_ROOT:-}" ]]; then
    local lib_dir
    lib_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    AE_ROOT="$(cd "${lib_dir}/../.." && pwd)"
    export AE_ROOT
  fi

  # Resolve agent root — check in-repo copy first, then sibling directory
  if [[ -z "${DPL_EVOLVE_AGENT_ROOT:-}" ]]; then
    local candidate
    # Prefer the bundled copy inside this AE repo (self-contained submission)
    candidate="${AE_ROOT}/src/dpl_evolve_agent"
    if [[ -d "${candidate}" ]]; then
      DPL_EVOLVE_AGENT_ROOT="${candidate}"
    else
      # Fallback: sibling directory (development layout)
      candidate="$(realpath -m "${AE_ROOT}/../dpl_evolve_agent")"
      if [[ -d "${candidate}" ]]; then
        DPL_EVOLVE_AGENT_ROOT="${candidate}"
      fi
    fi
  fi
  export DPL_EVOLVE_AGENT_ROOT

  # Resolve ORFS root
  if [[ -z "${ORFS_ROOT:-}" ]]; then
    local candidate
    candidate="$(realpath -m "${AE_ROOT}/../OpenROAD-flow-scripts")"
    if [[ -d "${candidate}/flow" && -d "${candidate}/tools/OpenROAD" ]]; then
      ORFS_ROOT="${candidate}"
    fi
  fi
  export ORFS_ROOT

  # Resolve state root
  if [[ -z "${DPL_EVOLVE_STATE_ROOT:-}" ]]; then
    local candidate
    candidate="$(realpath -m "${AE_ROOT}/../dpl_evolve_state")"
    if [[ -d "${candidate}" ]]; then
      DPL_EVOLVE_STATE_ROOT="${candidate}"
    fi
    # When dpl_evolve_state does not exist, leave STATE_ROOT unset.
    # Downstream lookups are guarded by [[ -n "${DPL_EVOLVE_STATE_ROOT:-}" ]].
  fi
  if [[ -n "${DPL_EVOLVE_STATE_ROOT:-}" ]]; then
    export DPL_EVOLVE_STATE_ROOT
  fi

  # Resolve Python
  if [[ -z "${DPL_EVOLVE_PYTHON:-}" ]]; then
    # Try the project venv first
    local venv_python
    venv_python="$(realpath -m "${AE_ROOT}/../.venvs/dplevolve/bin/python")"
    if [[ -x "${venv_python}" ]]; then
      DPL_EVOLVE_PYTHON="${venv_python}"
    elif command -v python3 >/dev/null 2>&1; then
      DPL_EVOLVE_PYTHON="$(command -v python3)"
    elif command -v python >/dev/null 2>&1; then
      DPL_EVOLVE_PYTHON="$(command -v python)"
    fi
  elif [[ "${DPL_EVOLVE_PYTHON}" != */* ]]; then
    # Make exports the default as a command name (usually "python3"). Resolve
    # it before the executable-path check below.
    DPL_EVOLVE_PYTHON="$(command -v "${DPL_EVOLVE_PYTHON}" 2>/dev/null || true)"
  fi
  export DPL_EVOLVE_PYTHON

  # Load machine-local modules and binary paths if available. The file is
  # generated by setup.sh and may have been created by another checkout.
  # Never let such a stale file replace paths already resolved for this
  # invocation or explicitly supplied by the caller.
  local resolved_ae_root="${AE_ROOT}"
  local resolved_agent_root="${DPL_EVOLVE_AGENT_ROOT}"
  local resolved_orfs_root="${ORFS_ROOT:-}"
  local resolved_state_root="${DPL_EVOLVE_STATE_ROOT:-}"
  local resolved_python="${DPL_EVOLVE_PYTHON}"
  local caller_yosys_set="${YOSYS_EXE+x}"
  local caller_yosys="${YOSYS_EXE:-}"
  local caller_openroad_set="${OPENROAD_EXE+x}"
  local caller_openroad="${OPENROAD_EXE:-}"
  if [[ -n "${DPL_EVOLVE_STATE_ROOT:-}" && -f "${DPL_EVOLVE_STATE_ROOT}/ae/environment.sh" ]]; then
    # shellcheck source=/dev/null
    source "${DPL_EVOLVE_STATE_ROOT}/ae/environment.sh"
  fi
  AE_ROOT="${resolved_ae_root}"
  DPL_EVOLVE_AGENT_ROOT="${resolved_agent_root}"
  ORFS_ROOT="${resolved_orfs_root}"
  DPL_EVOLVE_STATE_ROOT="${resolved_state_root}"
  DPL_EVOLVE_PYTHON="${resolved_python}"
  export AE_ROOT DPL_EVOLVE_AGENT_ROOT ORFS_ROOT DPL_EVOLVE_STATE_ROOT DPL_EVOLVE_PYTHON
  if [[ -n "${caller_yosys_set}" ]]; then
    YOSYS_EXE="${caller_yosys}"
  else
    # environment.sh may have been generated by another checkout sharing the
    # same state directory.  Rebuild its binary path from this invocation's
    # state root instead of retaining that checkout's lexical path.
    unset YOSYS_EXE
  fi
  if [[ -n "${caller_openroad_set}" ]]; then
    OPENROAD_EXE="${caller_openroad}"
  else
    # Resolve against the current prepared checkout below.  Besides removing
    # stale clone paths, this handles a recreated prepared commit whose tree is
    # identical but whose local commit ID changed.
    unset OPENROAD_EXE
  fi

  # Resolve Yosys binary (requires state root)
  if [[ -z "${YOSYS_EXE:-}" && -n "${DPL_EVOLVE_STATE_ROOT:-}" ]]; then
    local candidate
    candidate="${DPL_EVOLVE_STATE_ROOT}/yosys/8449dd470/bin/yosys"
    if [[ -x "${candidate}" ]]; then
      YOSYS_EXE="${candidate}"
    fi
  fi
  export YOSYS_EXE

  # Resolve OpenROAD binary (requires state root)
  if [[ -z "${OPENROAD_EXE:-}" && -n "${DPL_EVOLVE_STATE_ROOT:-}" ]]; then
    local candidate openroad_anchor
    candidate=""
    openroad_anchor=""
    if [[ -n "${ORFS_ROOT:-}" ]] \
       && git -C "${ORFS_ROOT}/tools/OpenROAD" rev-parse --git-dir >/dev/null 2>&1; then
      openroad_anchor="$(git -C "${ORFS_ROOT}/tools/OpenROAD" rev-parse --short HEAD 2>/dev/null || true)"
    fi
    if [[ -n "${openroad_anchor}" ]]; then
      candidate="${DPL_EVOLVE_STATE_ROOT}/openroad_core/${openroad_anchor}/install/OpenROAD/bin/openroad"
    fi
    if [[ -x "${candidate}" ]]; then
      OPENROAD_EXE="${candidate}"
    fi
  fi
  export OPENROAD_EXE

  # Verify critical paths
  local errors=0
  if [[ -z "${DPL_EVOLVE_AGENT_ROOT:-}" || ! -d "${DPL_EVOLVE_AGENT_ROOT}" ]]; then
    echo "[ERROR] DPL_EVOLVE_AGENT_ROOT not found: ${DPL_EVOLVE_AGENT_ROOT:-unset}" >&2
    errors=1
  fi
  if [[ -z "${ORFS_ROOT:-}" || ! -d "${ORFS_ROOT}/flow" ]]; then
    echo "[ERROR] ORFS_ROOT not found or missing flow/: ${ORFS_ROOT:-unset}" >&2
    errors=1
  fi
  if [[ -z "${DPL_EVOLVE_PYTHON:-}" || ! -x "${DPL_EVOLVE_PYTHON}" ]]; then
    echo "[ERROR] Python not found: ${DPL_EVOLVE_PYTHON:-unset}" >&2
    errors=1
  fi
  if [[ "${errors}" -ne 0 ]]; then
    echo "[ERROR] Environment resolution failed. Run 'make bootstrap' if ORFS is absent, then 'make build-tools'." >&2
    return 1
  fi

  return 0
}
