#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BOOTSTRAP_AGENT_ROOT="${DPL_EVOLVE_AGENT_ROOT:-$(cd "${SCRIPT_DIR}/../.." && pwd)}"
BOOTSTRAP_AGENT_ROOT="$(realpath -m "${BOOTSTRAP_AGENT_ROOT}")"
source "${BOOTSTRAP_AGENT_ROOT}/scripts/runtime_env.sh"
dpl_init_runtime "configure_openroad_variant_relink.sh"

ROOT_DIR="${ORFS_ROOT}"
OPENROAD_SRC="${ROOT_DIR}/tools/OpenROAD"
OPENROAD_ANCHOR_ID="$(git -C "${OPENROAD_SRC}" rev-parse --short HEAD)"

DEFAULT_CORE_ROOT="${DPL_EVOLVE_STATE_ROOT}/openroad_core/${OPENROAD_ANCHOR_ID}"
DEFAULT_VARIANT_ROOT="${DPL_EVOLVE_STATE_ROOT}/variants/default"

variant_root="$DEFAULT_VARIANT_ROOT"
build_dir=""
install_root=""
dpl_evolve_src=""
core_root="$DEFAULT_CORE_ROOT"

usage() {
  cat <<'EOF'
Usage: configure_openroad_variant_relink.sh [options]

Options:
  --variant-root PATH      Root directory for this variant. Default:
                           ${DPL_EVOLVE_STATE_ROOT}/variants/default
  --build-dir PATH         Explicit relink build directory override.
  --install-root PATH      Explicit install root override.
  --dpl-src PATH           External dpl_evolve source directory override.
  --core-root PATH         Common-core root. Default:
                           <state>/openroad_core/<openroad-head>
  --help                   Show this message.

Output:
  Writes <variant-root>/variant_env.sh with OPENROAD_CORE_ROOT,
  OPENROAD_BUILD_DIR, OPENROAD_INSTALL_ROOT, OPENROAD_BINARY,
  DPL_EVOLVE_SRC_DIR, and OPENROAD_VARIANT_MODE=relink.

Notes:
  This script does not read OPENROAD_* or DPL_EVOLVE_SRC_DIR environment
  variables as path defaults. Use the explicit options above so variant builds
  are reproducible from the command line and gate logs.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --variant-root)
      variant_root="$2"
      shift 2
      ;;
    --build-dir)
      build_dir="$2"
      shift 2
      ;;
    --install-root)
      install_root="$2"
      shift 2
      ;;
    --dpl-src)
      dpl_evolve_src="$2"
      shift 2
      ;;
    --core-root)
      core_root="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "[ERROR] Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

variant_root="$(realpath -m "$variant_root")"
build_dir="${build_dir:-${variant_root}/build}"
install_root="${install_root:-${variant_root}/install/OpenROAD}"
build_dir="$(realpath -m "$build_dir")"
install_root="$(realpath -m "$install_root")"
core_root="$(realpath -m "$core_root")"
variant_env="${variant_root}/variant_env.sh"

if [[ -z "$dpl_evolve_src" ]]; then
  dpl_evolve_src="${OPENROAD_SRC}/src/dpl_evolve"
fi
dpl_evolve_src="$(realpath -m "$dpl_evolve_src")"

if [[ ! -f "${dpl_evolve_src}/CMakeLists.txt" ]]; then
  echo "[ERROR] dpl_evolve source dir lacks CMakeLists.txt: ${dpl_evolve_src}" >&2
  exit 1
fi

mkdir -p "${variant_root}" "${build_dir}" "${install_root}/bin"

{
  echo "#!/usr/bin/env bash"
  echo "# Generated by configure_openroad_variant_relink.sh"
  echo "export OPENROAD_VARIANT_MODE=relink"
  echo "export OPENROAD_VARIANT_ROOT=$(printf '%q' "${variant_root}")"
  echo "export OPENROAD_CORE_ROOT=$(printf '%q' "${core_root}")"
  echo "export OPENROAD_BUILD_DIR=$(printf '%q' "${build_dir}")"
  echo "export OPENROAD_INSTALL_ROOT=$(printf '%q' "${install_root}")"
  echo "export OPENROAD_BINARY=$(printf '%q' "${install_root}/bin/openroad")"
  echo "export DPL_EVOLVE_SRC_DIR=$(printf '%q' "${dpl_evolve_src}")"
} > "${variant_env}"
chmod +x "${variant_env}"

echo "[INFO] Variant relink configure complete"
echo "[INFO] variant_root=${variant_root}"
echo "[INFO] core_root=${core_root}"
echo "[INFO] build_dir=${build_dir}"
echo "[INFO] install_root=${install_root}"
echo "[INFO] dpl_evolve_src=${dpl_evolve_src}"
echo "[INFO] variant_env=${variant_env}"
echo "[INFO] Use --openroad-binary ${install_root}/bin/openroad for evaluator runs."
