#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BOOTSTRAP_AGENT_ROOT="${DPL_EVOLVE_AGENT_ROOT:-$(cd "${SCRIPT_DIR}/../.." && pwd)}"
BOOTSTRAP_AGENT_ROOT="$(realpath -m "${BOOTSTRAP_AGENT_ROOT}")"
source "${BOOTSTRAP_AGENT_ROOT}/scripts/runtime_env.sh"
dpl_init_runtime "configure_openroad_core.sh"

ROOT_DIR="${ORFS_ROOT}"
OPENROAD_SRC="${ROOT_DIR}/tools/OpenROAD"
OPENROAD_ANCHOR_ID="$(git -C "${OPENROAD_SRC}" rev-parse --short HEAD)"

core_root="${DPL_EVOLVE_STATE_ROOT}/openroad_core/${OPENROAD_ANCHOR_ID}"
build_dir=""
install_root=""
generator=""

usage() {
  cat <<EOF
Usage: configure_openroad_core.sh [options]

Options:
  --core-root PATH         Core seed root. Default:
                           ${DPL_EVOLVE_STATE_ROOT}/openroad_core/${OPENROAD_ANCHOR_ID}
  --build-dir PATH         Explicit build directory override.
  --install-root PATH      Explicit install root override.
  --generator NAME         CMake generator override.
  --help                   Show this message.

Output:
  Writes <core-root>/core_env.sh with OPENROAD_CORE_ROOT,
  OPENROAD_BUILD_DIR, OPENROAD_INSTALL_ROOT, and OPENROAD_BINARY.

Notes:
  This script does not read OPENROAD_* environment variables as path defaults.
  Use explicit options for non-default core locations.
  The install root is still intentional: it gives variant relink jobs a stable
  seed OpenROAD binary at <install-root>/bin/openroad.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --core-root)
      core_root="$2"
      shift 2
      ;;
    --build-dir)
      build_dir="$2"
      shift 2
      ;;
    --install-root)
      install_root="$2"
      shift 2
      ;;
    --generator)
      generator="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "[ERROR] Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

core_root="$(realpath -m "${core_root}")"
build_dir="${build_dir:-${core_root}/build}"
install_root="${install_root:-${core_root}/install/OpenROAD}"
build_dir="$(realpath -m "${build_dir}")"
install_root="$(realpath -m "${install_root}")"
core_env="${core_root}/core_env.sh"

if [[ -z "${generator}" && -f "${ROOT_DIR}/tools/OpenROAD/build/CMakeCache.txt" ]]; then
  generator="$(sed -n 's/^CMAKE_GENERATOR:INTERNAL=//p' "${ROOT_DIR}/tools/OpenROAD/build/CMakeCache.txt" | tail -n 1)"
fi
generator="${generator:-Unix Makefiles}"

mkdir -p "${build_dir}" "${install_root}"

{
  echo "#!/usr/bin/env bash"
  echo "# Generated by configure_openroad_core.sh"
  echo "export OPENROAD_CORE_ROOT=$(printf '%q' "${core_root}")"
  echo "export OPENROAD_BUILD_DIR=$(printf '%q' "${build_dir}")"
  echo "export OPENROAD_INSTALL_ROOT=$(printf '%q' "${install_root}")"
  echo "export OPENROAD_BINARY=$(printf '%q' "${install_root}/bin/openroad")"
  echo "export CMAKE_GENERATOR=$(printf '%q' "${generator}")"
} > "${core_env}"
chmod +x "${core_env}"

echo "[INFO] Core configure complete"
echo "[INFO] core_root=${core_root}"
echo "[INFO] build_dir=${build_dir}"
echo "[INFO] install_root=${install_root}"
echo "[INFO] core_env=${core_env}"
echo "[INFO] Core binary will be ${install_root}/bin/openroad after build."
